
api: 
  finnhub:
    domain: "finnhub.io"
    endpoints1: 
      base: "/api/v1"
      stock: "/stock/profile2"
      quote: "/quote"

spring.datasource:
  url: jdbc:postgresql://localhost:5432/student
  username: postgres
  password: admin1234
spring.jpa:
  show-sql: true
  properties.hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
  hibernate.ddl-auto: update #update create table if not exist
                             #validate create table in database manually
                             

spring.sql.init: 
  mode: always